### ISSUE TITLE
Configs are not copied into bundle ZIP

### ISSUE THREAD

**Issue by sustacek** [david-truong/liferay-workspace#26]
The `com.liferay.workspace:1.0.2` does not copy configs into the ZIP bundle, neither from `common/` or `{environment}/`.

Not sure if this is the place, but there is no issues tab in the repo where the plugin is present (https://github.com/liferay/liferay-portal/tree/master/modules/sdk/gradle-plugins-workspace).

**Comment by gamerson** [comment]
@sustacek @david-truong @Ithildir i guess we could track workspace issues here, because this is sorta the testing grounds repository and when we have action items that turn into code in the portal repo we can cross-link.

**Comment by david-truong** [comment]
hmm I thought I fixed the issue in the latest workspace plugin...

**Comment by sustacek** [comment]
@david-truong let me check, I may have been using some old version of the plugin.

**Comment by sustacek** [comment]
@david-truong My bad, I must have been testing some older version of the plugin. It works as expected.
